controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    wheel_effort_controller:
      type: effort_controllers/JointGroupEffortController


wheel_effort_controller:
  ros__parameters:
    joints:
      - left_front_wheel_joint
      - left_behind_wheel_joint
      - right_front_wheel_joint
      - right_behind_wheel_joint
